version: 0.0
apiVersion: apps/v1
os: linux

files:
  - source: /
    destination: /tmp/app  # CodeDeploy copies your repository here
 AfterInstall:
    - location: scripts/deploy.sh       # Main deployment script (kubectl commands)
      timeout: 300
      runas: root
