version: 0.0
Resources:
  - myEKSDeployment:
      Type: AWS::EKS::KubernetesResource
      Properties:
        ClusterName: brain-tasks-clusters
        Namespace: default
        Manifest:
          - k8s/deployment.yaml
          - k8s/service.yaml
