version: 0.0
Resources:
  - TargetService:
      Type: AWS::EKS::Service
      Properties:
        ClusterName: brain-tasks-clusters
        Namespace: default
        # No specific name needed here; handled in deploy.sh
Hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
