version: 0.0
Resources:
  - TargetService:
      Type: AWS::EKS::Service
      Properties:
        TaskDefinition: ""
        LoadBalancerInfo:
          ContainerName: "brain-tasks-container"
          ContainerPort: 80

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: root
