version: 0.0
Resources:
  - TargetService:
      Type: Kubernetes
      Properties:
        Namespace: default
        TaskDefinition: deployment.yaml
        LoadBalancerInfo:
          ContainerName: brain-tasks-container
          ContainerPort: 80
