version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 118187397376.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest 118187397376.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 118187397376.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"brain-tasks-app","imageUri":"118187397376.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
