version: 0.0
apiVersion: apps/v1
os: linux

files:
  - source: /
    destination: /tmp/app  # temporary folder where CodeDeploy copies your repo

  AfterInstall:
    - location: scripts/deploy.sh        # this will contain your kubectl commands
      timeout: 300
      runas: root
