apiVersion: batch/v1
kind: Job
metadata:
  name: codebuild-deploy
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: codebuild-deployer  # important: uses IRSA
      restartPolicy: Never
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest  # small container with kubectl
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Update kubeconfig (not strictly necessary in-cluster)
              # Deploy the new image
              kubectl set image deployment/brain-tasks-deployment \
                brain-tasks-container=118187397376.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest \
                -n default;
              kubectl rollout status deployment/brain-tasks-deployment -n default
